# Generated by Codex on 2026-03-21

from django.db import migrations


ROLE_DEFINITIONS = (
    ("employee", "Empleado"),
    ("rrhh", "Recursos Humanos"),
    ("admin", "Administrador"),
)


def seed_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")

    for role_name, description in ROLE_DEFINITIONS:
        Role.objects.update_or_create(
            name=role_name,
            defaults={"description": description},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]
