# Generated by Codex on 2026-03-21

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.utils import timezone


ADMIN_EMAIL = "rolyscat@gmail.com"
ADMIN_DNI = "31415926L"
ADMIN_PASSWORD = "admin"
ADMIN_ROLE_NAME = "admin"


def seed_default_admin_user(apps, schema_editor):
    """Crea o promociona el usuario admin por defecto del proyecto."""
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")
    UserRole = apps.get_model("users", "UserRole")

    admin_role = Role.objects.get(name=ADMIN_ROLE_NAME)

    user, created = User.objects.get_or_create(
        email=ADMIN_EMAIL,
        defaults={
            "dni": ADMIN_DNI,
            "is_active": True,
            "is_staff": True,
            "is_superuser": True,
            "password": make_password(ADMIN_PASSWORD),
            "registered_at": timezone.now(),
        },
    )

    if not created:
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        if not user.dni:
            user.dni = ADMIN_DNI
        user.save(update_fields=["dni", "is_active", "is_staff", "is_superuser"])

    # Dejamos un unico rol funcional para este usuario: admin.
    UserRole.objects.filter(user=user).exclude(role=admin_role).delete()
    UserRole.objects.get_or_create(user=user, role=admin_role)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_seed_roles"),
    ]

    operations = [
        migrations.RunPython(seed_default_admin_user, migrations.RunPython.noop),
    ]
