# Generated by Django 6.0.3 on 2026-03-19 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de vacaciones',
                'verbose_name_plural': 'Estados de vacaciones',
                'db_table': 'vacation_statuses',
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('requested_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('employee_comment', models.TextField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True, null=True)),
                ('reprogram_reason', models.CharField(blank=True, choices=[('it', 'IT'), ('maternity', 'Maternidad')], max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='employees.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacation_requests', to='vacations.vacationstatus')),
            ],
            options={
                'verbose_name': 'Solicitud de vacaciones',
                'verbose_name_plural': 'Solicitudes de vacaciones',
                'db_table': 'vacation_requests',
            },
        ),
        migrations.CreateModel(
            name='VacationRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_changes', to=settings.AUTH_USER_MODEL)),
                ('vacation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='vacations.vacationrequest')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vacations.vacationstatus')),
                ('previous_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vacations.vacationstatus')),
            ],
            options={
                'verbose_name': 'Historial de solicitud',
                'verbose_name_plural': 'Historial de solicitudes',
                'db_table': 'vacation_request_histories',
            },
        ),
        migrations.AddIndex(
            model_name='vacationrequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='vac_req_emp_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationrequest',
            index=models.Index(fields=['status', 'request_date'], name='vac_req_status_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='check_end_date_gte_start_date'),
        ),
    ]
