# Generated by Codex on 2026-03-21

from django.db import migrations


VACATION_STATUS_DEFINITIONS = (
    ("pending",),
    ("approved",),
    ("rejected",),
)


def seed_vacation_statuses(apps, schema_editor):
    """Crea o actualiza los estados base usados por el flujo de vacaciones."""
    VacationStatus = apps.get_model("vacations", "VacationStatus")

    for (status_name,) in VACATION_STATUS_DEFINITIONS:
        VacationStatus.objects.update_or_create(
            name=status_name,
            defaults={"name": status_name},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("vacations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_vacation_statuses, migrations.RunPython.noop),
    ]
