"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent



env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = env('DEBUG')



# Application definition        


DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

LOCAL_APPS = [
    'apps.users',
    'apps.employees',
    'apps.vacations',
    'apps.notifications',
    'apps.audit',
    'apps.dashboard',
    'apps.core']


INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# URL configuration
ROOT_URLCONF = 'config.urls'

# Custom user model
AUTH_USER_MODEL = 'users.User'
# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'apps.users.backends.DNIBackend',
    'django.contrib.auth.backends.ModelBackend']


# WSGI application para servir la aplicación en producción con Gunicorn o similar
WSGI_APPLICATION = 'config.wsgi.application'




# Email configuration para enviar correos de activación y notificaciones

RESEND_API_KEY = env('RESEND_API_KEY', default='').strip()
EMAIL_PROVIDER = env('EMAIL_PROVIDER', default='console').strip().lower()
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=15)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.com')
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:8000')



# Caching configuration para limitar intentos de login y activación de cuenta

DEFAULT_CACHE_TIMEOUT = env.int('CACHE_TIMEOUT', default=300)
# Usamos cache en memoria para desarrollo, en producción se recomienda usar Redis o similar
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': env('LOCMEM_CACHE_LOCATION', default='lr-app-local'),
        'TIMEOUT': DEFAULT_CACHE_TIMEOUT,
    }
}
# Configuración de límites de intentos para login y activación de cuenta
LOGIN_RATE_LIMIT_ATTEMPTS = env.int('LOGIN_RATE_LIMIT_ATTEMPTS', default=5)
# Tiempo en segundos para bloquear después de alcanzar el límite de intentos
LOGIN_RATE_LIMIT_WINDOW = env.int('LOGIN_RATE_LIMIT_WINDOW', default=900)
# Configuración de límites de intentos para activación de cuenta
ACTIVATION_RATE_LIMIT_ATTEMPTS = env.int('ACTIVATION_RATE_LIMIT_ATTEMPTS', default=5)
# Tiempo en segundos para bloquear después de alcanzar el límite de intentos
ACTIVATION_RATE_LIMIT_WINDOW = env.int('ACTIVATION_RATE_LIMIT_WINDOW', default=900)



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


ROOT_URLCONF = 'config.urls'
