# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exporthistory",
            name="file_path",
        ),
        migrations.AddField(
            model_name="exporthistory",
            name="rows_snapshot_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exporthistory",
            name="columns_version",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
