# Generated by Django 6.0.3 on 2026-04-30 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_exporthistory_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
            },
        ),
        migrations.AlterModelOptions(
            name='exporthistory',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Historial de exportacion',
                'verbose_name_plural': 'Historial de exportaciones',
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audit_logs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
