# Generated by Django 6.0.3 on 2026-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_personal_admin_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Mensaje general'), ('vacation_request_status', 'Cambio de estado de solicitud'), ('vacation_request_submission', 'Nueva solicitud enviada'), ('admin_personal_message', 'Mensaje personal del administrador'), ('admin_broadcast_message', 'Aviso general del administrador')], default='info', max_length=40),
        ),
    ]
